# Generated by Django 5.2.7 on 2025-11-04 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="crop_type",
            field=models.CharField(
                choices=[
                    ("wheat", "Wheat"),
                    ("corn", "Corn"),
                    ("rice", "Rice"),
                    ("soybean", "Soybean"),
                    ("sunflower", "Sunflower"),
                ],
                max_length=10,
            ),
        ),
    ]
