# Generated by Django 5.2.8 on 2025-11-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmApp", "0003_crop_boundary_crop_location_farm_boundary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crop",
            name="planted_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="farm",
            name="size_hectares",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
