# Generated by Django 5.2.8 on 2025-11-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FarmApp", "0004_alter_crop_planted_area_alter_farm_size_hectares"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crop",
            name="location",
        ),
    ]
